apiVersion: v1
kind: Service
metadata:
  name: simpleapp
  namespace: default
  labels:
    app: simpleapp
spec:
  selector:
    app: simpleapp
  type: LoadBalancer
  ports:
  - name: web
    port: 8080
